import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  gradientBorder: {
    width: 343,
    height: 102,
    borderRadius: 16,
    padding: 1, // for gradient border
  },
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF7A", // 48%
    borderRadius: 16,
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 8,
    elevation: 8,
    padding: 12,
    justifyContent: "space-between",
  },
  titleRow: {
    width: 307,
    height: 28,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  titleText: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "700",
    color: "#58616A",
    letterSpacing: 0.09,
    fontFamily: "Pretendard",
  },
  button: {
    width: 71,
    height: 28,
    backgroundColor: "#F6F9FE",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#FFFFFF",
    paddingHorizontal: 8,
    paddingVertical: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#58616A",
  },
  statusBox: {
    width: 319,
    height: 42,
    backgroundColor: "#E6E8EA",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FFFFFF",
    paddingHorizontal: 12,
    justifyContent: "center",
  },
  statusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  statusText: {
    width: 129,
    height: 18,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.25,
    fontFamily: "Pretendard",
  },
  amountRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  amountCurrent: {
    width: 40,
    height: 22,
    fontSize: 15,
    fontWeight: "700",
    color: "#33363D",
    textAlign: "right",
    letterSpacing: 0.14,
    fontFamily: "Pretendard",
  },
  slash: {
    width: 6,
    height: 22,
    fontSize: 15,
    fontWeight: "500",
    color: "#CDD1D5",
    marginHorizontal: 2,
    letterSpacing: 0.14,
    fontFamily: "Pretendard",
  },
  amountTarget: {
    width: 37,
    height: 22,
    fontSize: 15,
    fontWeight: "500",
    color: "#464C53",
    letterSpacing: 0.14,
    fontFamily: "Pretendard",
  },
  ml: {
    width: 15,
    height: 18,
    fontSize: 13,
    fontWeight: "500",
    color: "#58616A",
    textAlign: "right",
    letterSpacing: 0.26,
    fontFamily: "Pretendard",
    marginLeft: 2,
  },
});

export default styles;
